import type { Metadata } from "next";
import { Poppins } from "next/font/google"; // import Poppins
import "./globals.css";
import Header from "@/layout/Header";
import { Footer } from "@/layout/Footer";
import NextTopLoader from 'nextjs-toploader';
import ReduxProvider from "@/providers/ReduxProvider";
import { Toaster } from "@/components/ui/sonner";
import BasicLayout from "@/layout/BasicLaypout";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "700"], // you can specify weights you need
  // style: ["normal", "italic"], // optionally specify styles
});

export const metadata: Metadata = {
  title: "Quartus Global Services",
  description: "Generated by create next app",
  icons: {
    icon: "/Fevicon.svg", // or "/favicon.png"
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/Fevicon.svg" type="image/svg+xml" />
      </head>
      <body className={`${poppins.variable} antialiased overflow-x-hidden`}>
        <ReduxProvider>
          <BasicLayout>
            {children}
          </BasicLayout>
          <Toaster />
        </ReduxProvider>
        <NextTopLoader />
      </body>
    </html>
  );
}
