import type { Metadata } from "next";
import { Poppins } from "next/font/google"; // import Poppins
import "./globals.css";
import Header from "@/layout/Header";
import { Footer } from "@/layout/Footer";
import NextTopLoader from 'nextjs-toploader';
import ReduxProvider from "@/providers/ReduxProvider";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "700"], // you can specify weights you need
  // style: ["normal", "italic"], // optionally specify styles
});

export const metadata: Metadata = {
  title: "Quartus global services",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <ReduxProvider>
            <Header />
          {children}
              <Footer />
        </ReduxProvider>
        <NextTopLoader />
      </body>
    </html>
  );
}
