export enum PERMISSIONS_LIST_ENUM {
  dashboard = 'dashboard',
  applications = 'applications',
  users = 'users',
  roles = 'roles',
  customers = 'customers',
  agencies = 'agencies',
  couriers = 'couriers',
  documents = 'documents',
  vehicles = 'vehicles',
  services = 'services',
  payments = 'payments',
  training = 'training',
  tickets = 'tickets',
  support = 'support',
  chat = 'chat',
  receipts = 'receipts',
}